# Enable C++ support
language: cpp

addons:
  apt:
    packages:
      - cmake
      - libgsl0-dev
      - libfftw3-3
      - libccfits-dev
      - libnfft3-dev
      - libarmadillo-dev
      - libboost-all-dev
  homebrew:
    packages: &macos_packages
      - cmake
      - pkgconfig
      - libomp
      - gsl
      - fftw
      - brewsci/science/ccfits
      - cfitsio
      - brewsci/science/nfft
      - armadillo
      - boost

matrix:
  include:
    - os: linux
      name: "GNU/Linux with GCC"
    - os: osx
      name: "macOS with AppleClang"
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - *macos_packages
    - os: osx
      name: "macOS with vanilla Clang"
      osx_image: xcode10.2
      env:
        - MATRIX_EVAL="CC=/usr/local/opt/llvm/bin/clang && CXX=/usr/local/opt/llvm/bin/clang++"
      addons:
        homebrew:
          packages:
            - llvm
            - *macos_packages

cache:
    directories:
      - /home/travis/build/CosmoStat/Glimpse/build/SPARSE2D
      - /home/travis/build/CosmoStat/Glimpse/build/NICAEA

before_install:
  - eval "${MATRIX_EVAL}"
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update && brew install catch2; fi
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      cd "$HOME"
      git clone https://github.com/catchorg/Catch2.git
      cd Catch2
      cmake -Bbuild -H. -DBUILD_TESTING=OFF
      sudo cmake --build build/ --target install
      cd "$TRAVIS_BUILD_DIR"
    fi

install: true

# Build steps
script:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      export LDFLAGS="-L$(brew --prefix libomp)/lib"
    fi
  - mkdir -p build && cd build
  - cmake -DBUILD_TESTING=ON ..
  - make VERBOSE=1
  - ./glimpse --version
  - ./test_wavelet_transform
  # - ./test_field
